name: MobileMorph CI

on:
  workflow_dispatch: 
    inputs:
        app_path:
            description: 'Path to the APK file or IPA file on your local machine (relative to repo)'
            required: true
            type: string
            default: 'insert path to .apk or .ipa file'
        platform:
            description: 'Platform (Android or iOS)'
            required: true
            default: 'Android or iOS'
            type: choice
            options:
              - android
              - ios

jobs:
  mobilemorph-local-analysis-scan:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m venv C:\envs\MobileMorph
        C:\envs\MobileMorph\Scripts\activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Static Analysis (Android)
      if: ${{ github.event.inputs.platform == 'android' }}
      run: python main.py --static --apk "${{ github.event.inputs.app_path }}"

    - name: Run Static Analysis (iOS)
      if: ${{ github.event.inputs.platform == 'ios' }}
      run: python main.py --static --ipa "${{ github.event.inputs.app_path }}"

    - name: Setup Testing Device (Android)
      if: ${{ github.event.inputs.platform == 'android' }}
      run: python main.py --setup-emulator

    - name: Run Dynamic Analysis (Android)
      if: ${{ github.event.inputs.platform == 'android' }}
      run: python main.py --dynamic --apk "${{ github.event.inputs.app_path }}"

    - name: Run Dynamic Analysis (iOS)
      if: ${{ github.event.inputs.platform == 'ios' }}
      run: python main.py --dynamic --ipa "${{ github.event.inputs.app_path }}"

    - name: Perform Vulnerability Exploitation (Android)
      if: ${{ github.event.inputs.platform == 'android' }}
      run: python main.py --exploit --apk "${{ github.event.inputs.app_path }}"
      env: 
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: analysis-reports
        path: ~/Downloads/MobileMorph/Reports
