name: MobileMorph CI

on:
  workflow_dispatch: 
    inputs:
        app_path:
            description: 'Path to the APK file or IPA file on your local machine (relative to repo)'
            required: true
            type: string
            default: 'insert path to .apk or .ipa file'
        platform:
            description: 'Platform (Android or iOS)'
            required: true
            default: 'Android or iOS'
            type: choice
            options:
              - android
              - ios

jobs:
  mobilemorph-analysis:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: pwsh
      run: |
        python -m venv env
        .\env\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Check Frida version compatibility
      shell: pwsh
      run : |
        python -c "
        from utils import frida_helpers;
        print('[INFO] Checking Frida version compatibility...');
        if not frida_helpers.check_frida_version_match():
          raise SystemExit('[ERROR] Frida versions do not match! Aborting workflow.');
        "
    - name: Run Static Analysis (APK/IPA)
      shell: bash
      run: |
        if [[ "${{ github.event.inputs.platform }}" == "android" ]]; then
          python main.py --static --apk "${{ github.event.inputs.app_path }}"
        elif [[ "${{ github.event.inputs.platform }}" == "ios" ]]; then
          python main.py --static --ipa "${{ github.event.inputs.app_path }}"
        else
          echo "Unknown platform input!" && exit 1
        fi

    - name: Setup Testing Device (Android)
      shell: bash
      run: |
        if [[ "${{ github.event.inputs.platform }}" == "android" ]]; then
          python main.py --setup-emulator --apk "${{ github.event.inputs.app_path }}"
        elif [[ "${{ github.event.inputs.platform }}" == "ios" ]]; then
          echo "Still in development...come back later" && exit 1
        else
          echo "Still in development...come back later" && exit 1
        fi

    - name: Verify Frida installation and device connection
      shell: bash
      run: |
        echo "[*] Checking Frida version and devices..."
        python -c "import frida; print('Frida version:', frida.__version__)"
        frida --version
        echo "[*] Listing connected devices:"
        frida-ls-devices || true

    - name: Run Dynamic Analysis (APK)
      shell: bash
      run: |
        if [[ "${{ github.event.inputs.platform }}" == "android" ]]; then
          python main.py --dynamic --apk "${{ github.event.inputs.app_path }}"
        elif [[ "${{ github.event.inputs.platform }}" == "ios" ]]; then
          python main.py --dynamic --ipa "${{ github.event.inputs.app_path }}"
        else
          echo "Still in development...come back later" && exit 1
        fi

    - name: Perform Vulnerability Exploitation (APK)
      shell: bash
      run: |
        if [[ "${{ github.event.inputs.platform }}" == "android" ]]; then
          python main.py --exploit --apk "${{ github.event.inputs.app_path }}"
        else
          echo "Unknown platform input!" && exit 1
        fi
      env: 
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
            name: analysis-reports
            path: ~/Downloads/MobileMorph/Reports
