name: MobileMorph CI

on:
  workflow_dispatch: 
    inputs:
        apk_path:
            description: 'Path to the APK file on your local machine (relative to repo)'
            required: true
            default: 'injuredAndroid.apk'

jobs:
  local-analysis:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Powershell Execution Policy (for local runner)
      shell: powershell
      run: |
        $currentPolicy = Get-ExecutionPolicy -Scope Process
        if ($currentPolicy -ne "RemoteSigned") {
          Write-Host "Current Execution Policy: $currentPolicy - setting to RemoteSigned for this session."
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
        } else {
          Write-Host "Execution Policy already set to RemoteSigned." 
        }

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Static Analysis (APK)
      run: |
        python main.py --static --apk "${{github.event.inputs.apk_path}}"

    - name: Run Dynamic Analysis (APK)
      run: |
        python main.py --dynamic --apk "${{github.event.inputs.apk_path}}"
      env: 
        GH_TOKEN: ${{secrets.GH_TOKEN}} # Use the token as an environment variable

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
            name: analysis-reports
            path: ~/Downloads/MobileMorph/Reports
